services:
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.146.1@sha256:f6e429c1052ab50f85a7afa5f7e32f25931697751622b0e1f453d10f79a1df3c
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    environment:
      - GRAFANA_CLOUD_USERNAME
      - GRAFANA_CLOUD_API_KEY
      - GRAFANA_CLOUD_ENDPOINT
