services:
  otelcol:
    image: otel/opentelemetry-collector-contrib:0.109.0@sha256:af0f72b2d2493fc17f06cf3bc136548240cd7ebb2c8b1c8a7be6f3eb03068389
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    environment:
      - GRAFANA_CLOUD_USERNAME
      - GRAFANA_CLOUD_API_KEY
      - GRAFANA_CLOUD_ENDPOINT
